return {
    {
        'nvim-treesitter/nvim-treesitter',
        build = ':TSUpdate',
        event = 'VeryLazy',
        main = 'nvim-treesitter',
        opts = {
            ensure_installed = {
                'bash',
                'c',
                'css',
                'dockerfile',
                'go',
                'haskell',
                'html',
                'javascript',
                'json',
                'lua',
                'markdown',
                'python',
                'ruby',
                'rust',
                'tsx',
                'typescript',
                'vim',
                'vimdoc',
                'yaml',
            },
        },
    },
}
